export { AssistantWidget, WidgetPlacement } from './assistant-widget';
export type { AssistantWidgetProps } from './assistant-widget';
export { AssistantOrb } from './orb/assistant-orb';
export type { AssistantOrbProps } from './orb/assistant-orb';
export { AssistantPanel } from './panel/assistant-panel';
export type { AssistantPanelProps } from './panel/assistant-panel';
export { AssistantTranscript } from './transcript/assistant-transcript';
export type { AssistantTranscriptProps } from './transcript/assistant-transcript';
export { MessageBubble } from './transcript/message-bubble';
export { ToolChip } from './transcript/tool-chip';
export type { MessageEntry } from './transcript/message-entry';
export type { ToolEntry } from './transcript/tool-entry';
export { StatusLine } from './panel/status-line';
export { AssistantComposer } from './panel/assistant-composer';
export { AssistantControls } from './panel/assistant-controls';
export type { MessageBubbleProps } from './transcript/message-bubble';
export type { ToolChipProps } from './transcript/tool-chip';
export { useWidgetTheme } from './theme/widget-theme-context';
export { useWidgetStrings } from './strings/widget-strings-context';
export { mergeTheme } from './theme/merge-theme';
export { mergeStrings } from './strings/merge-strings';
export { defaultTheme } from './theme/default-theme';
export type { AssistantTheme } from './theme/assistant-theme';
export type { AssistantThemeOverride } from './theme/merge-theme';
export { defaultStrings } from './strings/default-strings';
export type { AssistantStrings } from './strings/assistant-strings';
export type { AssistantStringsOverride } from './strings/merge-strings';
export { WidgetThemeContext } from './theme/widget-theme-context';
export { WidgetStringsContext } from './strings/widget-strings-context';
