const fs = require('fs');
const path = require('path');
const { withDangerousMod } = require('@expo/config-plugins');

/**
 * Stops Android's Force Dark from repainting the splash screen in dark mode.
 *
 * **The symptom.** In dark mode the launch screen showed a lighter orange
 * SQUARE floating on a darker orange field. Measured from a device screenshot:
 * the square was `#EE8941` — the splash background of the day — and the
 * surround was `#A14900`, a colour that appears nowhere in this repo.
 *
 * The splash is now a fixed off-white (`#F5F5F4`, in both light and dark), which
 * makes this opt-out matter MORE rather than less: Force Dark darkens a white
 * window far more visibly than it darkened an orange one, and the logo plate
 * would still be untouched. The seam would simply be starker.
 *
 * **Why.** `Theme.SplashScreen` descends from a light theme, so on Android 10+
 * the system may apply Force Dark: it algorithmically darkens the WINDOW's
 * background in dark mode, and it does not touch bitmaps. `expo-splash-screen`
 * bakes `backgroundColor` into the generated `splashscreen_logo.png` as an
 * opaque plate — verified: the source `splash-icon.png` has a fully transparent
 * corner, the generated one's corner is opaque `rgba(238,137,65,255)`. So the
 * window was darkened, the plate was not, and the seam became a visible square.
 *
 * Nothing was misconfigured: `values/colors.xml` and `values-night/colors.xml`
 * both carry `#EE8941`, which is why this was invisible from the config alone.
 *
 * **Why a NIGHT override and not a patch to `values/styles.xml`.** Two earlier
 * attempts — `withAndroidStyles`, then a dangerous mod rewriting the file — both
 * patched `AppTheme` and both silently lost the item on
 * `Theme.App.SplashScreen`, because expo-splash-screen writes that style after
 * every mod this plugin can register. Verified against the generated
 * `styles.xml` each time, not the plugin's return value: the config is not the
 * artifact. A `values-night/styles.xml` is a different resource file, so
 * nothing downstream rewrites it, and the resource merger gives it precedence
 * in dark mode — which is the only mode Force Dark exists in. The override is
 * therefore both durable and exactly as narrow as the problem.
 *
 * `android/` is git-ignored and regenerated on every CI run, so this cannot be
 * a hand-edit. Idempotent: the file is written wholesale each prebuild.
 *
 * @see https://developer.android.com/develop/ui/views/theming/darktheme#force-dark
 */
const NIGHT_STYLES_PATH = ['app', 'src', 'main', 'res', 'values-night', 'styles.xml'];

/**
 * The night-mode themes, mirroring what expo-splash-screen generates for the
 * light configuration plus the Force Dark opt-out.
 *
 * The three splash items are resource REFERENCES, not values — the colour and
 * the drawable are still whatever the light configuration and
 * `values-night/colors.xml` resolve to, so the brand colour stays in one place.
 * They are repeated here because an Android style override replaces the whole
 * style: omitting them would fall back to `Theme.SplashScreen`'s defaults and
 * lose the background and the logo, which is a worse bug than the one being
 * fixed. `plugins/__tests__` pins the list against that.
 */
const NIGHT_STYLES = `<?xml version="1.0" encoding="utf-8"?>
<!--
  Generated by plugins/withAndroidSplashForceDark.js — do not edit.
  Opts the launch themes out of Android's Force Dark, which would otherwise
  darken the splash WINDOW while leaving the splash logo bitmap alone, showing
  the seam between them as a lighter square.
-->
<resources>
  <style name="AppTheme" parent="Theme.AppCompat.DayNight.NoActionBar">
    <item name="android:forceDarkAllowed">false</item>
  </style>
  <style name="Theme.App.SplashScreen" parent="Theme.SplashScreen">
    <item name="windowSplashScreenBackground">@color/splashscreen_background</item>
    <item name="windowSplashScreenAnimatedIcon">@drawable/splashscreen_logo</item>
    <item name="postSplashScreenTheme">@style/AppTheme</item>
    <item name="android:forceDarkAllowed">false</item>
  </style>
</resources>
`;

/** Every item the night splash theme must carry to stay equivalent to the day one. */
const REQUIRED_SPLASH_ITEMS = [
  'windowSplashScreenBackground',
  'windowSplashScreenAnimatedIcon',
  'postSplashScreenTheme',
  'android:forceDarkAllowed',
];

module.exports = function withAndroidSplashForceDark(config) {
  return withDangerousMod(config, [
    'android',
    (cfg) => {
      const file = path.join(cfg.modRequest.platformProjectRoot, ...NIGHT_STYLES_PATH);
      fs.mkdirSync(path.dirname(file), { recursive: true });
      fs.writeFileSync(file, NIGHT_STYLES, 'utf8');
      return cfg;
    },
  ]);
};

module.exports.NIGHT_STYLES = NIGHT_STYLES;
module.exports.REQUIRED_SPLASH_ITEMS = REQUIRED_SPLASH_ITEMS;
