import CryptoKit
import Foundation

// The Swift third of the envelope parity suite. Compiled together with
// `modules/recipely-assistant-kit/ios/Envelope.swift` by
// `scripts/verify-swift-envelope.sh`, which is the only way to run it: CryptoKit
// is Apple-only, so this cannot live in the JS gate chain that CI runs on Linux.
//
// Why a script and not XCTest: the Xcode project is generated by `expo prebuild`
// and a test target added to it is erased on the next run — silently, leaving a
// suite that looks present in git and never executes. A script in the repo
// cannot be deleted by a code generator.
//
// `@main` rather than top-level statements: those are only allowed in a file
// called `main.swift`, and this file is compiled alongside the source it tests.

private struct Vector {
  let name: String
  let plaintext: String
  let ivBase64: String
  let payloadBase64: String

  init(_ entry: [String: Any]) {
    name = entry["name"] as? String ?? "unnamed"
    plaintext = entry["plaintext"] as? String ?? ""
    ivBase64 = entry["ivBase64"] as? String ?? ""
    payloadBase64 = entry["payloadBase64"] as? String ?? ""
  }
}

@main
struct EnvelopeParityHarness {
  static func main() {
    let path = CommandLine.arguments.dropFirst().first ?? ""
    guard let data = FileManager.default.contents(atPath: path) else {
      fail("cannot read fixture at \(path)")
    }
    guard
      let fixture = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
      let keyHex = fixture["keyHex"] as? String,
      let rawVectors = fixture["vectors"] as? [[String: Any]],
      let rawRejects = fixture["rejects"] as? [[String: Any]]
    else {
      fail("fixture is not the shape this harness expects")
    }
    guard let key = try? Envelope.key(fromHex: keyHex) else {
      fail("fixture key is not 32 bytes of hex")
    }

    let vectors = rawVectors.map(Vector.init)
    let rejects = rawRejects.map(Vector.init)

    opens(vectors, key)
    seals(vectors, key)
    refuses(rejects, key)
    refusesBadKeys()
  }

  private static func opens(_ vectors: [Vector], _ key: SymmetricKey) {
    for vector in vectors {
      guard let opened = try? Envelope.open(payload: vector.payloadBase64, iv: vector.ivBase64, key: key) else {
        fail("open(\(vector.name)) threw")
      }
      guard opened == vector.plaintext else {
        fail("open(\(vector.name)) returned different text than OpenSSL sealed")
      }
    }
    print("  ✓ opens \(vectors.count) payloads OpenSSL sealed")
  }

  /// Byte-exact rather than a round trip: a round trip passes against two
  /// implementations of the same mistake. The Turkish vector is the one that
  /// fails here the moment the encoding is anything but UTF-8.
  private static func seals(_ vectors: [Vector], _ key: SymmetricKey) {
    for vector in vectors {
      guard
        let ivData = Data(base64Encoded: vector.ivBase64),
        let nonce = try? AES.GCM.Nonce(data: ivData)
      else {
        fail("fixture iv for \(vector.name) is not a 12-byte nonce")
      }
      guard let sealed = try? Envelope.seal(json: vector.plaintext, key: key, nonce: nonce) else {
        fail("seal(\(vector.name)) threw")
      }
      guard sealed.payload == vector.payloadBase64 else {
        fail("seal(\(vector.name)) produced different bytes than OpenSSL")
      }
      guard sealed.iv == vector.ivBase64 else {
        fail("seal(\(vector.name)) returned a different nonce than it was given")
      }
    }
    print("  ✓ seals \(vectors.count) payloads byte-for-byte as OpenSSL did")
  }

  private static func refuses(_ rejects: [Vector], _ key: SymmetricKey) {
    for reject in rejects {
      do {
        _ = try Envelope.open(payload: reject.payloadBase64, iv: reject.ivBase64, key: key)
        fail("open(\(reject.name)) returned bytes instead of throwing")
      } catch {
        continue
      }
    }
    print("  ✓ refuses \(rejects.count) malformed or tampered payloads")
  }

  private static func refusesBadKeys() {
    for bad in ["abc", String(repeating: "z", count: 64)] {
      do {
        _ = try Envelope.key(fromHex: bad)
        fail("key(fromHex: \"\(bad.prefix(8))…\") was accepted")
      } catch {
        continue
      }
    }
    print("  ✓ refuses a key that is not 32 bytes of hex")
  }

  private static func fail(_ message: String) -> Never {
    FileHandle.standardError.write(Data("  ✗ \(message)\n".utf8))
    exit(1)
  }
}
