import Foundation

// The Swift half of the Spotlight check, compiled together with
// `modules/recipely-assistant-kit/ios/RecipelySpotlightIndex.swift` by
// `scripts/verify-swift-spotlight.sh`.
//
// Why a script and not XCTest: the same reason the envelope suite is one — the
// Xcode project is generated by `expo prebuild`, and a test target added to it
// is erased on the next run, silently.
//
// What it is FOR: the two pure pieces either side of a Spotlight tap. The
// identifier is what iOS hands back in `CSSearchableItemActivityIdentifier`,
// and the URL is what the app is then re-opened with — get either wrong and the
// result opens the app on whatever screen it happened to be on, which reads to
// the user as the search having done nothing.

private var failures: [String] = []

private func expect(_ actual: String?, _ expected: String?, _ what: String) {
  if actual != expected {
    failures.append("  ✗ \(what): expected \(expected ?? "nil"), got \(actual ?? "nil")")
  } else {
    print("  ✓ \(what)")
  }
}

@main
struct VerifySpotlight {
  static func main() {
    print("spotlight identifiers (Swift · CoreSpotlight):")

    expect(
      RecipelySpotlightIndex.recipeId(fromSearchableItemIdentifier: "recipe:r-baklava"),
      "r-baklava",
      "reads the recipe id back out of a searchable item"
    )
    expect(
      RecipelySpotlightIndex.recipeId(fromSearchableItemIdentifier: "note:r-baklava"),
      nil,
      "ignores an identifier that is not one of ours"
    )
    expect(
      RecipelySpotlightIndex.recipeURL(recipeId: "r-baklava", scheme: "recipely")?.absoluteString,
      "recipely://assistant/run?id=openRecipe&action=openRecipe&arg=r-baklava",
      "opens the recipe on the same road Android's shortcuts use"
    )
    expect(
      RecipelySpotlightIndex.recipeURL(recipeId: "r-baklava", scheme: "recipely-dev")?.absoluteString,
      "recipely-dev://assistant/run?id=openRecipe&action=openRecipe&arg=r-baklava",
      "follows the dev build's scheme without naming it"
    )
    // An id is a backend key, not a word — but a build with a stray space in one
    // must not produce a URL that silently truncates at it.
    expect(
      RecipelySpotlightIndex.recipeURL(recipeId: "fırında tavuk", scheme: "recipely")?.absoluteString,
      "recipely://assistant/run?id=openRecipe&action=openRecipe&arg=f%C4%B1r%C4%B1nda%20tavuk",
      "escapes an id the query string would otherwise cut short"
    )
    expect(
      RecipelySpotlightIndex.recipeURL(recipeId: "r-baklava", scheme: "")?.absoluteString,
      nil,
      "does nothing when the build declares no scheme"
    )

    if failures.isEmpty { return }
    print(failures.joined(separator: "\n"))
    exit(1)
  }
}
