import CryptoKit
import Foundation

// The Swift third of the envelope parity suite. Compiled together with
// `modules/recipely-assistant-kit/ios/Envelope.swift` by
// `scripts/verify-swift-envelope.sh`, which is the only way to run it: CryptoKit
// is Apple-only, so this cannot live in the JS gate chain that CI runs on Linux.
//
// Why a script and not XCTest: the Xcode project is generated by `expo prebuild`
// and a test target added to it is erased on the next run — silently, leaving a
// suite that looks present in git and never executes. A script in the repo
// cannot be deleted by a code generator.
//
// `@main` rather than top-level statements: those are only allowed in a file
// called `main.swift`, and this file is compiled alongside the source it tests.

private struct Vector {
  let name: String
  let plaintext: String
  let ivBase64: String
  let payloadBase64: String
  /// Present on rejection cases: the refusal this implementation must answer with.
  let failure: String?

  /// A missing field fails rather than defaulting. An empty `plaintext` would
  /// have made a vector pass against an implementation that returned nothing —
  /// a vacuous pass is worse than a red test, because it reads as coverage.
  init(_ entry: [String: Any]) throws {
    guard
      let name = entry["name"] as? String,
      let ivBase64 = entry["ivBase64"] as? String,
      let payloadBase64 = entry["payloadBase64"] as? String
    else {
      throw HarnessError.malformedVector
    }
    self.name = name
    self.ivBase64 = ivBase64
    self.payloadBase64 = payloadBase64
    self.plaintext = entry["plaintext"] as? String ?? ""
    self.failure = entry["failure"] as? String
  }
}

private enum HarnessError: Error {
  case malformedVector
}

/// Maps the fixture's refusal name onto this implementation's failure.
///
/// Unknown names fail rather than being skipped: a fixture that grows a case this
/// side cannot answer must say so, not quietly verify two of three.
private func expectedFailure(_ name: String) -> Envelope.Failure? {
  switch name {
  case "authenticationFailed": return .authenticationFailed
  case "badIvLength": return .badIvLength
  case "payloadShorterThanTag": return .payloadShorterThanTag
  case "notBase64": return .notBase64
  default: return nil
  }
}

@main
struct EnvelopeParityHarness {
  static func main() {
    let path = CommandLine.arguments.dropFirst().first ?? ""
    guard let data = FileManager.default.contents(atPath: path) else {
      fail("cannot read fixture at \(path)")
    }
    guard
      let fixture = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
      let keyHex = fixture["keyHex"] as? String,
      let rawVectors = fixture["vectors"] as? [[String: Any]],
      let rawRejects = fixture["rejects"] as? [[String: Any]]
    else {
      fail("fixture is not the shape this harness expects")
    }
    guard let key = try? Envelope.key(fromHex: keyHex) else {
      fail("fixture key is not 32 bytes of hex")
    }

    guard
      let vectors = try? rawVectors.map(Vector.init),
      let rejects = try? rawRejects.map(Vector.init)
    else {
      fail("a fixture vector is missing a field this harness requires")
    }

    opens(vectors, key)
    seals(vectors, key)
    refuses(rejects, key)
    refusesBadKeys()
    speaksTheMessageRoute(key)
  }

  /// The intent's request and reply, checked against what the backend reads.
  ///
  /// The first draft sealed `{ message, languageCode }` where `decrypt-body`
  /// requires `{ data: { message, languageCode } }`: every headless answer would
  /// have been a 400, and the intent would have opened the app each time as if
  /// the network were down. Nothing else runs this Swift before a device does.
  private static func speaksTheMessageRoute(_ key: SymmetricKey) {
    guard
      let wire = try? RecipelyAssistantWire.request(message: "kaç kalori?", languageCode: "tr", key: key),
      let envelope = try? JSONSerialization.jsonObject(with: wire) as? [String: Any],
      let payload = envelope["payload"] as? String,
      let iv = envelope["iv"] as? String,
      let plain = try? Envelope.open(payload: payload, iv: iv, key: key),
      let root = try? JSONSerialization.jsonObject(with: Data(plain.utf8)) as? [String: Any]
    else {
      fail("the message request is not an envelope this key opens")
    }
    guard
      root.keys.sorted() == ["data"],
      let body = root["data"] as? [String: String],
      body == ["message": "kaç kalori?", "languageCode": "tr"]
    else {
      fail("the message request is not { data: { message, languageCode } }, which decrypt-body requires")
    }

    // Shaped as `encrypt-response` seals them: `{ data: <body> }`, nothing else.
    let cases: [(String, RecipelyAssistantWire.Reply?)] = [
      (#"{"data":{"reply":"Bakıyorum.","action":{"name":"search","arg":"mercimek"}}}"#,
       .init(text: "Bakıyorum.", action: "search", arg: "mercimek")),
      (#"{"data":{"reply":"250 kalori."}}"#,
       .init(text: "250 kalori.", action: nil, arg: nil)),
      (#"{"data":{"reply":"Tamam.","action":{"name":"","arg":"x"}}}"#,
       .init(text: "Tamam.", action: nil, arg: nil)),
      (#"{"data":{"reply":"","action":{"name":"search"}}}"#,
       .init(text: "", action: "search", arg: nil)),
      (#"{"data":{"reply":""}}"#, nil),
    ]
    for (body, expected) in cases {
      guard
        let sealed = try? Envelope.seal(json: body, key: key),
        let response = try? JSONSerialization.data(withJSONObject: ["payload": sealed.payload, "iv": sealed.iv])
      else {
        fail("could not seal a reply fixture")
      }
      guard RecipelyAssistantWire.reply(from: response, key: key) == expected else {
        fail("reply(\(body)) did not read as \(String(describing: expected))")
      }
    }
    print("  ✓ speaks /assistant/message: { data: … } out, reply and action back")
  }

  private static func opens(_ vectors: [Vector], _ key: SymmetricKey) {
    for vector in vectors {
      guard let opened = try? Envelope.open(payload: vector.payloadBase64, iv: vector.ivBase64, key: key) else {
        fail("open(\(vector.name)) threw")
      }
      guard opened == vector.plaintext else {
        fail("open(\(vector.name)) returned different text than OpenSSL sealed")
      }
    }
    print("  ✓ opens \(vectors.count) payloads OpenSSL sealed")
  }

  /// Byte-exact rather than a round trip: a round trip passes against two
  /// implementations of the same mistake. The Turkish vector is the one that
  /// fails here the moment the encoding is anything but UTF-8.
  private static func seals(_ vectors: [Vector], _ key: SymmetricKey) {
    for vector in vectors {
      guard
        let ivData = Data(base64Encoded: vector.ivBase64),
        let nonce = try? AES.GCM.Nonce(data: ivData)
      else {
        fail("fixture iv for \(vector.name) is not a 12-byte nonce")
      }
      guard let sealed = try? Envelope.seal(json: vector.plaintext, key: key, nonce: nonce) else {
        fail("seal(\(vector.name)) threw")
      }
      guard sealed.payload == vector.payloadBase64 else {
        fail("seal(\(vector.name)) produced different bytes than OpenSSL")
      }
      guard sealed.iv == vector.ivBase64 else {
        fail("seal(\(vector.name)) returned a different nonce than it was given")
      }
    }
    print("  ✓ seals \(vectors.count) payloads byte-for-byte as OpenSSL did")
  }

  /// Asserts the NAMED refusal, not merely that something was thrown.
  ///
  /// Measured: deleting the IV-length guard from `Envelope.swift` left this
  /// harness fully green, because CryptoKit's `AES.GCM.Nonce(data:)` refuses an
  /// 11-byte nonce on its own — a different refusal that satisfied a `catch` which
  /// asked nothing. The fixture names the expected one so the three
  /// implementations are pinned to refuse for the same REASON.
  private static func refuses(_ rejects: [Vector], _ key: SymmetricKey) {
    for reject in rejects {
      guard let name = reject.failure else {
        fail("reject vector \(reject.name) does not name the refusal it expects")
      }
      guard let expected = expectedFailure(name) else {
        fail("fixture names a refusal this harness cannot map: \(name)")
      }
      do {
        _ = try Envelope.open(payload: reject.payloadBase64, iv: reject.ivBase64, key: key)
        fail("open(\(reject.name)) returned bytes instead of throwing")
      } catch let thrown as Envelope.Failure {
        guard thrown == expected else {
          fail("open(\(reject.name)) refused with \(thrown) where \(expected) was required")
        }
      } catch {
        fail("open(\(reject.name)) threw \(error), which is not an Envelope.Failure")
      }
    }
    print("  ✓ refuses \(rejects.count) payloads, each for the named reason")
  }

  private static func refusesBadKeys() {
    // `"+a"` x 32 is 64 characters and was ACCEPTED before the alphabet check:
    // Swift's `UInt8(_:radix:)` allows a leading sign. `"-1"` x 32 is the same
    // hole pointing the other way, which is the one Kotlin had.
    for bad in ["abc", String(repeating: "z", count: 64), String(repeating: "+a", count: 32), String(repeating: "-1", count: 32)] {
      do {
        _ = try Envelope.key(fromHex: bad)
        fail("key(fromHex: \"\(bad.prefix(8))…\") was accepted")
      } catch {
        continue
      }
    }
    print("  ✓ refuses a key that is not 32 bytes of hex")
  }

  private static func fail(_ message: String) -> Never {
    FileHandle.standardError.write(Data("  ✗ \(message)\n".utf8))
    exit(1)
  }
}
